Update files

diff --git a/Assignment2/poornames b/Assignment2/poornames
--- a/Assignment2/poornames
+++ b/Assignment2/poornames
@@ -17,13 +17,16 @@ check_filenames () {
 	exit
     fi
 
-    # If dir has a trailing '/', remove it for Rule checking
-    dir=${dir%/}
-
+    # If dir does not have a trailing '/', add one
+    if [ "$dir" = ${dir%/} ]
+    then
+	dir="$dir/"
+    fi
+    
     # Exclude the input directory dir (first line of find output)
-    filenames=`find "$dir" -maxdepth 1 -exec basename {} \; | tail -n +2`
+    local filenames=`find "$dir" -maxdepth 1 -exec basename {} \; | tail -n +2`
 
-    violations=""
+    local violations=""
     for filename in $filenames
     do
 	# Rule 1
@@ -47,26 +50,23 @@ check_filenames () {
             violations="$violations$filename\n"
 	fi
 	# Check for read permissions on directories
-	if [ ! -L "$dir/$filename" ] && [ -d "$dir/$filename" ] && \
-	       [ ! -r "$dir/$filename" ]
+	if [ ! -L "$dir$filename" ] && [ -d "$dir$filename" ] && \
+	       [ ! -r "$dir$filename" ]
 	then
-	    echo "The directory $dir/$filename cannot be read." 1>&2
+	    echo "The directory $dir$filename cannot be read." 1>&2
 	fi
 	# Recurse if directory is readable and '-r' option is used
-	if [ ! -L "$dir/$filename" ] && [ -d "$dir/$filename" ] && \
-	       [ -r "$dir/$filename" ] && [ "$recurse" = "-r" ]
+	if [ ! -L "$dir$filename" ] && [ -d "$dir$filename" ] && \
+	       [ -r "$dir$filename" ] && [ "$recurse" = "-r" ]
         then
-            check_filenames "$dir/$filename" -r
+            check_filenames "$dir$filename" -r
         fi
     done
 
-    # Add a trailing '/' for displaying output
-    dir="$dir/"
-
     # Find case insensitive duplicates
     # Exclude the input directory dir (first line of find output)
-    duplicates=`find "$dir" -maxdepth 1 -exec basename {} \; | tail -n +2`
-    duplicates=`echo -e "$duplicates" | uniq -iD`
+    local duplicates=`find "$dir" -maxdepth 1 -exec basename {} \; | tail -n +2`
+    duplicates=`echo -e "$duplicates" | sort -f | uniq -iD`
 
     # Deduplicate any lines that violated a Rule 1-4 and was a duplicate
     violations=`echo -e "$violations$duplicates" | sort -u`
